# Lab1: Introduction to Python and Jupyter Notebooks
In today's lab, you'll learn:
1. How to navigate Jupyter notebooks;
2. Basic concepts and features of the Python language and system

In [3]:
#importing needed libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from  datascience import *

from sklearn.model_selection import train_test_split, LeaveOneOut, KFold, cross_val_score
from random import choices
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors    import KNeighborsClassifier 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix, classification_report, precision_score, accuracy_score
#import statsmodels.api as sm

import warnings
warnings.filterwarnings('ignore')

In [4]:
Pricedf = pd.read_csv("price.csv")
Pricedf['State']


#i want the aveage of columns 7-81
#cityMatrix = Pricedf['City']

#Ptofcity =  Pricedf[['displacement','horsepower','weight','acceleration','year']]

cityMatrix = Pricedf['City'].to_numpy()
valmatrix = Pricedf.iloc[:,7:]

#Valuematrix = Pricedf[['November 2010','December 2010','January 2011','February 2011','March 2011','April 2011','May 2011','June 2011','July 2011','August 2011','September 2011','October 2011','November 2011','December 2011','January 2012','February 2012','March 2012','April 2012','May 2012','June 2012','July 2012','August 2012','September 2012','October 2012','November 2012','December 2012','January 2013','February 2013','March 2013','April 2013','May 2013','June 2013','July 2013','August 2013','September 2013','October 2013','November 2013','December 2013','January 2014','February 2014','March 2014','April 2014','May 2014','June 2014','July 2014','August 2014','September 2014','October 2014','November 2014','December 2014','January 2015','February 2015','March 2015','April 2015','May 2015','June 2015','July 2015','August 2015','September 2015','October 2015','November 2015','December 2015','January 2016','February 2016','March 2016','April 2016','May 2016','June 2016','July 2016','August 2016','September 2016','October 2016','November 2016','December 2016','January 2017']]
#Values = Valuematrix.to_numpy()
#Values[1].mean()
valmatrix = valmatrix.dropna()
valmatrix.iloc[0].mean()

rentnumpy = valmatrix.to_numpy()
listofnames = []
count = 0
for i in rentnumpy:
    mean = i[0:].mean()
    
    if (mean<= 3000) and (mean >= 1000):
        listofnames.append(cityMatrix[count])
        
    count+=1
        
len(listofnames)

8126

In [18]:
crime1 = pd.read_csv('crimedata/CrimeOneYearofData.csv')
crime2 = pd.read_csv('crimedata/CrimeOneYearofData (1).csv')
crime3 = pd.read_csv('crimedata/CrimeOneYearofData (2).csv')
crime4 = pd.read_csv('crimedata/CrimeOneYearofData (3).csv')
crime5 = pd.read_csv('crimedata/CrimeOneYearofData (4).csv')
crime6 = pd.read_csv('crimedata/CrimeOneYearofData (5).csv')
crime7 = pd.read_csv('crimedata/CrimeOneYearofData (6).csv')
crime8 = pd.read_csv('crimedata/CrimeOneYearofData (7).csv')
#crime1
stateandCrime = crime1['State']
stateandCrime = pd.concat([stateandCrime, crime1['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime2['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime3['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime4['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime5['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime6['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime7['Violent Crime rate']], axis=1)
stateandCrime = pd.concat([stateandCrime, crime8['Violent Crime rate']], axis=1)
#stateandCrime now has data frome crime in every state 


numcrime = stateandCrime.to_numpy()
meancrime = []
print(numcrime)
for i in numcrime:
    mean = i[1:].mean()
    meancrime.append(mean)

meancrime
dfmeancrime = pd.DataFrame(data=meancrime, index=[0,1,2,3,4,5,6,7,8,9,
                                                  10,11,12,13,14,15,16,17,18,19,
                                                  20,21,22,23,24,25,26,27,28,29,
                                                  30,31,32,33,34,35,36,37,38,39,
                                                  40,41,42,43,44,45,46,47,48,49,50], columns=["mean"])
stateandCrime = pd.concat([stateandCrime, dfmeancrime], axis=1)
stateandCrime

[['Alabama' 448.9 452.8 450.1 383.7 419.8 450.3 431.0 427.4]
 ['Alaska' 661.3 652.1 633.4 635.3 610.1 604.1 638.7 635.8]
 ['Arizona' 518.0 485.6 426.5 413.6 414.2 428.6 415.6 399.9]
 ['Arkansas' 537.1 513.0 515.8 503.5 482.3 469.6 463.2 480.1]
 ['California' 524.1 504.2 473.3 439.6 411.2 423.5 402.6 396.1]
 ['Colorado' 351.8 353.9 338.8 323.7 314.4 307.4 305.4 309.1]
 ['Connecticut' 301.1 306.7 300.9 282.0 275.7 283.5 262.2 236.9]
 ['Delaware' 705.4 708.6 645.4 623.3 566.4 550.5 500.7 489.1]
 ['District of Columbia' 1415.1 1437.7 1348.9 1326.8 1200.8 1241.8 1296.4
  1244.4]
 ['Florida' 722.6 688.9 612.5 541.3 514.6 487.0 469.3 540.5]
 ['Georgia' 491.5 488.9 428.0 402.3 374.6 380.0 375.4 377.3]
 ['Hawaii' 276.1 272.5 274.1 264.3 251.4 243.0 254.4 259.2]
 ['Idaho' 256.2 241.5 246.2 220.5 202.2 209.8 215.2 212.2]
 ['Illinois' 533.2 525.4 497.2 444.9 424.0 416.2 403.1 370.0]
 ['Indiana' 335.8 337.6 334.0 323.3 331.8 344.8 359.6 365.3]
 ['Iowa' 300.2 288.1 282.1 268.5 257.3 265.6 273.0 273.5]
 ['Kansas' 458.6 412.3 406.6 370.8 355.7 356.7 342.8 348.6]
 ['Kentucky' 290.7 297.2 255.0 243.9 239.6 224.9 210.9 211.6]
 ['Louisiana' 740.4 671.4 642.9 555.3 554.6 496.3 521.2 514.7]
 ['Maine' 118.8 119.4 119.9 122.1 123.3 122.4 132.5 127.8]
 ['Maryland' 641.9 628.2 590.0 546.3 493.5 477.3 475.4 446.1]
 ['Massachusetts' 441.7 463.8 462.6 468.9 427.3 407.0 406.4 391.4]
 ['Michigan' 533.8 514.9 499.8 493.0 442.8 455.0 452.2 427.3]
 ['Minnesota' 289.6 265.4 244.5 235.7 230.5 230.9 234.4 229.1]
 ['Mississippi' 291.3 304.3 286.3 269.3 269.0 260.1 277.5 278.5]
 ['Missouri' 560.7 502.4 492.9 457.7 447.5 451.3 433.7 442.9]
 ['Montana' 379.8 311.4 287.0 275.8 276.1 278.8 288.1 323.7]
 ['Nebraska' 311.3 312.3 289.4 278.3 253.6 258.8 264.8 280.4]
 ['Nevada' 754.9 729.7 705.2 663.0 568.1 608.6 605.0 635.6]
 ['New Hampshire' 144.1 156.1 160.4 167.4 217.3 215.0 223.2 196.1]
 ['New Jersey' 328.6 326.5 311.4 307.5 307.9 290.1 288.9 261.2]
 ['New Mexico' 675.7 653.5 632.4 588.0 572.7 559.6 622.5 597.4]
 ['New York' 414.4 397.9 384.4 394.4 397.2 406.3 393.8 381.8]
 ['North Carolina' 466.1 467.6 404.5 362.7 346.3 353.5 341.0 329.5]
 ['North Dakota' 209.9 224.6 266.4 229.5 248.1 245.7 273.4 265.1]
 ['Ohio' 355.4 352.0 331.9 314.7 305.2 301.5 291.4 284.9]
 ['Oklahoma' 504.1 531.5 503.4 481.4 457.5 474.4 446.1 406.0]
 ['Oregon' 293.9 261.4 260.6 251.4 249.3 247.1 242.8 232.3]
 ['Pennsylvania' 416.7 410.0 382.3 366.5 362.4 355.5 335.1 314.1]
 ['Rhode Island' 229.1 252.8 254.3 257.4 246.1 253.0 257.3 219.2]
 ['South Carolina' 785.7 731.0 675.2 602.2 596.9 560.5 508.5 497.7]
 ['South Dakota' 241.9 276.9 218.7 268.9 255.6 323.8 323.2 326.5]
 ['Tennessee' 755.0 722.7 666.0 612.0 607.8 638.5 585.8 608.4]
 ['Texas' 510.4 508.0 491.0 448.4 408.6 408.6 410.3 405.9]
 ['Utah' 239.9 225.3 215.4 213.5 197.1 208.0 228.9 215.6]
 ['Vermont' 129.1 137.5 134.6 131.0 147.6 142.3 123.6 99.3]
 ['Virginia' 272.8 257.8 230.8 214.2 197.6 191.5 197.8 196.2]
 ['Washington' 336.5 334.2 336.3 313.5 295.3 298.1 290.0 285.2]
 ['West Virginia' 276.8 275.9 305.2 301.2 296.3 320.1 305.2 302.0]
 ['Wisconsin' 291.5 275.5 259.1 248.9 249.9 283.9 280.7 290.3]
 ['Wyoming' 257.1 249.7 219.7 197.9 219.4 201.3 207.8 195.5]]

,State,Violent Crime rate,Violent Crime rate,Violent Crime rate,Violent Crime rate,Violent Crime rate,Violent Crime rate,Violent Crime rate,Violent Crime rate,mean
0,Alabama,448.9,452.8,450.1,383.7,419.8,450.3,431.0,427.4,433.0000
1,Alaska,661.3,652.1,633.4,635.3,610.1,604.1,638.7,635.8,633.8500
2,Arizona,518.0,485.6,426.5,413.6,414.2,428.6,415.6,399.9,437.7500
3,Arkansas,537.1,513.0,515.8,503.5,482.3,469.6,463.2,480.1,495.5750
4,California,524.1,504.2,473.3,439.6,411.2,423.5,402.6,396.1,446.8250
5,Colorado,351.8,353.9,338.8,323.7,314.4,307.4,305.4,309.1,325.5625
6,Connecticut,301.1,306.7,300.9,282.0,275.7,283.5,262.2,236.9,281.1250
7,Delaware,705.4,708.6,645.4,623.3,566.4,550.5,500.7,489.1,598.6750
8,District of Columbia,1415.1,1437.7,1348.9,1326.8,1200.8,1241.8,1296.4,1244.4,1313.9875
9,Florida,722.6,688.9,612.5,541.3,514.6,487.0,469.3,540.5,572.0875
10,Georgia,491.5,488.9,428.0,402.3,374.6,380.0,375.4,377.3,414.7500
11,Hawaii,276.1,272.5,274.1,264.3,251.4,243.0,254.4,259.2,261.8750
12,Idaho,256.2,241.5,246.2,220.5,202.2,209.8,215.2,212.2,225.4750
13,Illinois,533.2,525.4,497.2,444.9,424.0,416.2,403.1,370.0,451.7500
14,Indiana,335.8,337.6,334.0,323.3,331.8,344.8,359.6,365.3,341.5250
15,Iowa,300.2,288.1,282.1,268.5,257.3,265.6,273.0,273.5,276.0375
16,Kansas,458.6,412.3,406.6,370.8,355.7,356.7,342.8,348.6,381.5125
17,Kentucky,290.7,297.2,255.0,243.9,239.6,224.9,210.9,211.6,246.7250
18,Louisiana,740.4,671.4,642.9,555.3,554.6,496.3,521.2,514.7,587.1000
19,Maine,118.8,119.4,119.9,122.1,123.3,122.4,132.5,127.8,123.2750
20,Maryland,641.9,628.2,590.0,546.3,493.5,477.3,475.4,446.1,537.3375
21,Massachusetts,441.7,463.8,462.6,468.9,427.3,407.0,406.4,391.4,433.6375
22,Michigan,533.8,514.9,499.8,493.0,442.8,455.0,452.2,427.3,477.3500
23,Minnesota,289.6,265.4,244.5,235.7,230.5,230.9,234.4,229.1,245.0125
24,Mississippi,291.3,304.3,286.3,269.3,269.0,260.1,277.5,278.5,279.5375
25,Missouri,560.7,502.4,492.9,457.7,447.5,451.3,433.7,442.9,473.6375
26,Montana,379.8,311.4,287.0,275.8,276.1,278.8,288.1,323.7,302.5875
27,Nebraska,311.3,312.3,289.4,278.3,253.6,258.8,264.8,280.4,281.1125
28,Nevada,754.9,729.7,705.2,663.0,568.1,608.6,605.0,635.6,658.7625
29,New Hampshire,144.1,156.1,160.4,167.4,217.3,215.0,223.2,196.1,184.9500
30,New Jersey,328.6,326.5,311.4,307.5,307.9,290.1,288.9,261.2,302.7625
31,New Mexico,675.7,653.5,632.4,588.0,572.7,559.6,622.5,597.4,612.7250
32,New York,414.4,397.9,384.4,394.4,397.2,406.3,393.8,381.8,396.2750
33,North Carolina,466.1,467.6,404.5,362.7,346.3,353.5,341.0,329.5,383.9000
34,North Dakota,209.9,224.6,266.4,229.5,248.1,245.7,273.4,265.1,245.3375
35,Ohio,355.4,352.0,331.9,314.7,305.2,301.5,291.4,284.9,317.1250
36,Oklahoma,504.1,531.5,503.4,481.4,457.5,474.4,446.1,406.0,475.5500
37,Oregon,293.9,261.4,260.6,251.4,249.3,247.1,242.8,232.3,254.8500
38,Pennsylvania,416.7,410.0,382.3,366.5,362.4,355.5,335.1,314.1,367.8250
39,Rhode Island,229.1,252.8,254.3,257.4,246.1,253.0,257.3,219.2,246.1500
40,South Carolina,785.7,731.0,675.2,602.2,596.9,560.5,508.5,497.7,619.7125
41,South Dakota,241.9,276.9,218.7,268.9,255.6,323.8,323.2,326.5,279.4375
42,Tennessee,755.0,722.7,666.0,612.0,607.8,638.5,585.8,608.4,649.5250
43,Texas,510.4,508.0,491.0,448.4,408.6,408.6,410.3,405.9,448.9000
44,Utah,239.9,225.3,215.4,213.5,197.1,208.0,228.9,215.6,217.9625
45,Vermont,129.1,137.5,134.6,131.0,147.6,142.3,123.6,99.3,130.6250
46,Virginia,272.8,257.8,230.8,214.2,197.6,191.5,197.8,196.2,219.8375
47,Washington,336.5,334.2,336.3,313.5,295.3,298.1,290.0,285.2,311.1375
48,West Virginia,276.8,275.9,305.2,301.2,296.3,320.1,305.2,302.0,297.8375
49,Wisconsin,291.5,275.5,259.1,248.9,249.9,283.9,280.7,290.3,272.4750
50,Wyoming,257.1,249.7,219.7,197.9,219.4,201.3,207.8,195.5,218.5500

In [10]:
df = pd.read_csv('uscities.csv')
cities1 = df['city']
cities = (df['city']).to_numpy()
population = (df['population']).to_numpy()
density = (df['density']).to_numpy()
state_name = (df['state_name']).to_numpy()
county_name = (df['county_name']).to_numpy()
a = np.matrix([cities, population, density, state_name, county_name])

cities1

0           New York
1        Los Angeles
2            Chicago
3              Miami
4             Dallas
            ...
29483         Caputa
29484         Hamill
29485         Loomis
29486    Bijou Hills
29487            Ola
Name: city, Length: 29488, dtype: object

In [11]:
b = np.vstack(cities)
c = np.vstack(population)
d = np.vstack(density)
e = np.vstack(state_name)
f = np.vstack(county_name)
vmatrix = np.concatenate((b,c,d,e,f),axis=1)
print (vmatrix)

[['New York' '18713220' '10715.0' 'New York' 'New York']
 ['Los Angeles' '12750807' '3276.0' 'California' 'Los Angeles']
 ['Chicago' '8604203' '4574.0' 'Illinois' 'Cook']
 ...
 ['Loomis' '0' '0.0' 'South Dakota' 'Davison']
 ['Bijou Hills' '0' '0.0' 'South Dakota' 'Brule']
 ['Ola' '0' '0.0' 'South Dakota' 'Brule']]

In [12]:
response = []

for i in vmatrix:
    if (float(i[1]) <= 49999):
        response = np.append(response, 0)
    elif (float(i[1]) > 50000 and float(i[1]) <= 349999):
        response = np.append(response, 1)
    else:
        response = np.append(response, 2) 
        
response = np.vstack(response)

area_def = []
for i in vmatrix:
    if(float(i[1]) >= 50000 or float(i[2]) >= 1000):
        area_def = np.append(area_def, 2) # urban areas
    elif (float(i[1]) >= 2500 and float(i[1]) < 50000):
    #else:
        area_def = np.append(area_def, 1) # urban clusters
    elif (float(i[1]) < 2500 or float(i[2]) < 500):
        area_def = np.append(area_def, 0) # rural areas
area_def = np.vstack(area_def)
        
result = np.concatenate((vmatrix, response,area_def), axis=1)

In [13]:
#meancrimecolumn = []
#for

In [14]:
type(listofnames)

list

In [15]:
for i in range(len(listofnames)):
    if listofnames[i] == cities1.iloc[i]:
        print(listofnames[i])

New York
Los Angeles
Chicago
Kansas City

In [16]:
listofnames

['New York',
 'Los Angeles',
 'Chicago',
 'Houston',
 'Philadelphia',
 'Phoenix',
 'Las Vegas',
 'San Antonio',
 'San Diego',
 'Dallas',
 'San Jose',
 'San Francisco',
 'Indianapolis',
 'Austin',
 'Detroit',
 'Memphis',
 'Charlotte',
 'El Paso',
 'Boston',
 'Seattle',
 'Baltimore',
 'Denver',
 'Washington',
 'Nashville',
 'Milwaukee',
 'Tucson',
 'Portland',
 'Oklahoma City',
 'Omaha',
 'Albuquerque',
 'Fresno',
 'Mesa',
 'Long Beach',
 'Kansas City',
 'Virginia Beach',
 'Colorado Springs',
 'Oakland',
 'Tulsa',
 'Cleveland',
 'Honolulu',
 'Baton Rouge',
 'New Orleans',
 'Arlington',
 'Raleigh',
 'Tampa',
 'Aurora',
 'Saint Louis',
 'Corpus Christi',
 'Cincinnati',
 'Riverside',
 'Marietta',
 'Anchorage',
 'Bakersfield',
 'Saint Paul',
 'Toledo',
 'Lexington',
 'Tallahassee',
 'Stockton',
 'Buffalo',
 'Chandler',
 'Louisville',
 'Henderson',
 'Modesto',
 'Mobile',
 'Jersey City',
 'Orlando',
 'Norfolk',
 'Saint Petersburg',
 'Pensacola',
 'Fort Wayne',
 'Greensboro',
 'Lincoln',
 'San Bernardino',
 'Corona',
 'Chesapeake',
 'Hialeah',
 'Madison',
 'Garland',
 'Knoxville',
 'Laredo',
 'North Las Vegas',
 'Lawrenceville',
 'Springfield',
 'Arlington',
 'Irving',
 'Gilbert',
 'Scottsdale',
 'Winston-Salem',
 'Irvine',
 'Richmond',
 'Bradenton',
 'Montgomery',
 'Santa Rosa',
 'Des Moines',
 'Spokane',
 'Augusta',
 'Grand Rapids',
 'Gainesville',
 'Woodbridge',
 'Ocala',
 'Boise',
 'Birmingham',
 'Salt Lake City',
 'Huntington Beach',
 'Akron',
 'Worcester',
 'Moreno Valley',
 'Port Saint Lucie',
 'Brownsville',
 'Amarillo',
 'Lancaster',
 'Fort Collins',
 'Shreveport',
 'Evansville',
 'Chattanooga',
 'Columbus',
 'Aurora',
 'Ontario',
 'Jackson',
 'Rancho Cucamonga',
 'Newport News',
 'Garden Grove',
 'Killeen',
 'Roanoke',
 'Tempe',
 'Vancouver',
 'Huntsville',
 'El Cajon',
 'Palmdale',
 'Topeka',
 'Pueblo',
 'Cape Coral',
 'Springfield',
 'Murfreesboro',
 'Clarksville',
 'Naperville',
 'Pomona',
 'Kansas City',
 'Boynton Beach',
 'Syracuse',
 'Salem',
 'Hollywood',
 'Paterson',
 'Lakewood',
 'Alexandria',
 'Dayton',
 'Yuma',
 'Sunnyvale',
 'Visalia',
 'Las Cruces',
 'Charleston',
 'Beaumont',
 'Pasadena',
 'Bridgeport',
 'Eugene',
 'Escondido',
 'Sugar Land',
 'Round Rock',
 'Hampton',
 'Pasadena',
 'Torrance',
 'Columbia',
 'Mesquite',
 'Fullerton',
 'Warren',
 'West Valley City',
 'Renton',
 'Canton',
 'Metairie',
 'Santa Maria',
 'Edinburg',
 'Inglewood',
 'Orange',
 'New Haven',
 'Cumming',
 'Flint',
 'Abilene',
 'Compton',
 'McAllen',
 'Bellevue',
 'Saginaw',
 'Bloomington',
 'Olathe',
 'Miramar',
 'Queen Creek',
 'East Los Angeles',
 'Hamilton',
 'Hartford',
 'Stamford',
 'Savannah',
 'Simi Valley',
 'Concord',
 'Sterling Heights',
 'Elizabeth',
 'Frisco',
 'Joliet',
 'Billings',
 'Allentown',
 'Amherst',
 'Santa Fe',
 'Vallejo',
 'Independence',
 'Santa Clara',
 'Cary',
 'Cypress',
 'Conroe',
 'Surprise',
 'Berkeley',
 'Hemet',
 'Norman',
 'Falls Church',
 'Downey',
 'Waco',
 'Thornton',
 'Frederick',
 'Westminster',
 'Lansing',
 'Victorville',
 'Waterbury',
 'New Port Richey',
 'Temecula',
 'Miami Gardens',
 'Costa Mesa',
 'Athens',
 'Manchester',
 'Rochester',
 'Ventura',
 'Murrieta',
 'Peoria',
 'Chico',
 'Ann Arbor',
 'Lowell',
 'Gainesville',
 'Clovis',
 'Cambridge',
 'Sparks',
 'Roseville',
 'Norwalk',
 'Redding',
 'El Monte',
 'College Station',
 'Burbank',
 'West Jordan',
 'Nampa',
 'Everett',
 'Spartanburg',
 'Tuscaloosa',
 'Clearwater',
 'Wilmington',
 'Pompano Beach',
 'Davenport',
 'Hesperia',
 'Grand Junction',
 'Stone Mountain',
 'Fargo',
 'Edison',
 'West Covina',
 'Carlsbad',
 'Vacaville',
 'Bowling Green',
 'Lewisville',
 'Beaverton',
 'Saint Augustine',
 'West Palm Beach',
 'Columbia',
 'Erie',
 'Cedar Rapids',
 'Jacksonville',
 'Norcross',
 'Wichita Falls',
 'Fairfield',
 'Madera',
 'Merced',
 'Daly City',
 'Perris',
 'Livonia',
 'San Leandro',
 'Dearborn',
 'South Gate',
 'Sandy Springs',
 'Albany',
 'Portsmouth',
 'Longview',
 'Laurel',
 'Orange Park',
 'Vero Beach',
 'Spring Hill',
 'Duluth',
 'Davie',
 'West Chester',
 'Columbia',
 'Newton',
 'Albany',
 'Lakeland',
 'Napa',
 'Lakewood Township',
 'Centennial',
 'Riverview',
 'Kenosha',
 'Arvada',
 'Lawton',
 'Annapolis',
 'Clinton Township',
 'Rialto',
 'Indio',
 'Highlands Ranch',
 'New Bedford',
 'Federal Way',
 'Hillsboro',
 'Sandy',
 'Champaign',
 'Bethlehem Township',
 'Greeley',
 'Canton',
 'Meridian',
 'Santa Monica',
 'Kennewick',
 'Yakima',
 'Muncie',
 'Valdosta',
 'Plantation',
 'Lithonia',
 'Kalamazoo',
 'Lynchburg',
 'McDonough',
 'Terre Haute',
 'Livermore',
 'Bryan',
 'Decatur',
 'Duluth',
 'Orem',
 'Anderson',
 'Miami Beach',
 'Fall River',
 'Concord',
 'Flagstaff',
 'Allen',
 'Franklin',
 'Herndon',
 'Midlothian',
 'Toms River',
 'Pearland',
 'Nashua',
 'Edmond',
 'Chapel Hill',
 'Williamsburg',
 'Reading',
 'Cicero',
 'Holland',
 'Sioux City',
 'Bowie',
 'Boulder',
 'Norwalk',
 'Citrus Heights',
 'Buena Park',
 'Town of Poughkeepsie',
 'Gary',
 'Troy',
 'Germantown',
 'Richmond',
 'Hawthorne',
 'San Tan Valley',
 'Johnson City',
 'Chino',
 'Parma',
 'Gulfport',
 'Suffolk',
 'Macomb Township',
 'Spokane Valley',
 'Lexington',
 'Farmington Hills',
 'Ogden',
 'Alhambra',
 'Leesburg',
 'Kent',
 'Acworth',
 'Loveland',
 'Cleveland',
 'Douglasville',
 'Redwood City',
 'Danbury',
 'Arden-Arcade',
 'Parker',
 'Hattiesburg',
 'Lees Summit',
 'Dalton',
 'Woodstock',
 'Ashburn',
 'Watsonville',
 'Owensboro',
 'Roswell',
 'Lakewood',
 'Longmont',
 'Newnan',
 'Medford',
 'Fort Smith',
 'Cranston',
 'Camden',
 'Melbourne',
 'Tustin',
 'Brooklyn Park',
 'Bloomington',
 'Conyers',
 "Town 'n' Country",
 'Whittier',
 'Milton',
 'Eau Claire',
 'Thousand Oaks',
 'Upland',
 'Iowa City',
 'Manteca',
 'Greenwood',
 'Arlington Heights',
 'Mission',
 'Sumter',
 'Bethlehem',
 'Mountain View',
 'Bellflower',
 'Plant City',
 'Westminster',
 'Warner Robins',
 'Covina',
 'Shelby Township',
 'Pflugerville',
 'Waukegan',
 'Conway',
 'Redmond',
 'High Point',
 'Somerville',
 'Cheektowaga',
 'Maryville',
 'Saint George',
 'Pittsburg',
 'Valparaiso',
 'Redlands',
 'Oviedo',
 'Palm Coast',
 'Saint Joseph',
 'North Charleston',
 'League City',
 'Deltona',
 'Turlock',
 'Saint Charles',
 'Lexington',
 'Porterville',
 'Sanford',
 'Kendall',
 'Tulare',
 'Baldwin Park',
 'Lynnwood',
 'Lake Forest',
 'Wilmington',
 'San Ramon',
 'New Rochelle',
 'Huntington',
 'Camarillo',
 'Springfield',
 'Pharr',
 'Petaluma',
 'La Mesa',
 'Simpsonville',
 'Hammond',
 'Palm Harbor',
 'Mount Pleasant',
 'Cherry Hill',
 'Brandon',
 'Kingsport',
 'Council Bluffs',
 'Asheville',
 'Pleasanton',
 'Greenville',
 'Lauderhill',
 'Apple Valley',
 'Kirkland',
 'Waipahu',
 'Redondo Beach',
 'Yuba City',
 'Bismarck',
 'Greer',
 'Mooresville',
 'Salisbury',
 'Centreville',
 'San Marcos',
 'Pasco',
 'Rome',
 'Bremerton',
 'Spring Valley',
 'O Fallon',
 'Passaic',
 'Schaumburg',
 'Ellicott City',
 'Plymouth',
 'Waldorf',
 'Marysville',
 'Casper',
 'Lynwood',
 'Avondale',
 'Temple',
 'Kokomo',
 'San Rafael',
 'Palo Alto',
 'Milpitas',
 'Portland',
 'Jonesboro',
 'Union City',
 'Union City',
 'Dubuque',
 'Palatine',
 'Tomball',
 'The Woodlands',
 'North Little Rock',
 'Waterloo',
 'Port Charlotte',
 'Vienna',
 'East Orange',
 'Weston',
 'Chino Hills',
 'Bellingham',
 'Salisbury',
 'Manhattan',
 'Alameda',
 'Eagan',
 'Daytona Beach',
 'Pico Rivera',
 'Racine',
 'Bel Air',
 'Denham Springs',
 'York Township',
 'Bossier City',
 'Gastonia',
 'Conway',
 'Corvallis',
 'West Bloomfield',
 'Brunswick',
 'Mount Vernon',
 'Venice',
 'Bethesda',
 'Bolingbrook',
 'Meridian',
 'Lorain',
 'Midland',
 'Maple Grove',
 'Baytown',
 'West Hartford',
 'Aiken',
 'Glen Allen',
 'Statesville',
 'Taylor',
 'Ames',
 'Columbus',
 'Goodyear',
 'North Port',
 'Coon Rapids',
 'Orland Park',
 'North Bergen',
 'Rosemead',
 'Des Plaines',
 'Laguna Niguel',
 'San Marcos',
 'Arcadia',
 'Florence',
 'Harrisonburg',
 'Woodbury',
 'Vineland',
 'Burnsville',
 'Georgetown',
 'La Habra',
 'Carmel',
 'Eden Prairie',
 'Jefferson City',
 'Valley Stream',
 'Hamden',
 'Hendersonville',
 'Bristol',
 'West Allis',
 'Punta Gorda',
 'Medina',
 'Meriden',
 'Reston',
 'Taylorsville',
 'Dundalk',
 'Lancaster',
 'Waltham',
 'Haverhill',
 'Bellevue',
 'Lakewood',
 'San Gabriel',
 'Jupiter',
 'Pontiac',
 'Fountainbleau',
 'Malden',
 'Gardena',
 'Royal Oak',
 'Novato',
 'Manchester',
 'Florence-Graham',
 'Huntsville',
 'Oak Lawn',
 'Newport Beach',
 'Ewa Beach',
 'Kissimmee',
 'Pasadena',
 'Skokie',
 'Carson City',
 'Gilroy',
 'Fort Mill',
 'Dearborn Heights',
 'San Clemente',
 'Brentwood',
 'Deland',
 'Bozeman',
 'Mansfield',
 'Rapid City',
 'Texarkana',
 'Fayetteville',
 'Berwyn',
 'Rocklin',
 'Saint Peters',
 'Gretna',
 'North Richland Hills',
 'Woodland',
 'Annandale',
 'Mechanicsville',
 'Richmond',
 'West Des Moines',
 'Land O Lakes',
 'South San Francisco',
 'Lake Elsinore',
 'Saint Cloud',
 'Lompoc',
 'Lancaster',
 'Farmington',
 'Davis',
 'White Plains',
 'Rancho Cordova',
 'Chicopee',
 'Town of Hempstead',
 'Bensalem',
 'Midwest City',
 'Florence',
 'Azusa',
 'Lilburn',
 'Danville',
 'Muskegon Township',
 'Carmichael',
 'Grand Forks',
 'Roswell',
 'Albany',
 'Colton',
 'Newark',
 'Loveland',
 'Goose Creek',
 'Noblesville',
 'Irvington',
 'New Castle',
 'Deerfield Beach',
 'Altamonte Springs',
 'Montebello',
 'Westminster',
 'Cupertino',
 'Titusville',
 'Margate',
 'Wayne',
 'Town of Hamburg',
 'Wheaton',
 'Valrico',
 'Snohomish',
 'Kettering',
 'Layton',
 'Weymouth',
 'Fairfield',
 'Santee',
 'Statesboro',
 'Broomfield',
 'Coconut Creek',
 'Lake Havasu City',
 'Lutz',
 'Mount Prospect',
 'Atascocita',
 'Port Orange',
 'West Haven',
 'Rockville',
 'Jackson',
 'Union',
 'Stillwater',
 'Fountain Valley',
 'Wyoming',
 'Piscataway Township',
 'Millcreek Township',
 'Lagrange',
 'Morristown',
 'Upper Darby Township',
 'Chillicothe',
 'Harlingen',
 'New Iberia',
 'Novi',
 'Klamath Falls',
 'Town of Newburgh',
 'South Whittier',
 'Aloha',
 'New Brunswick',
 'Parsippany-Troy Hills Township',
 'Tinley Park',
 'Kailua',
 'Issaquah',
 'Castle Rock',
 'Easley',
 'Maricopa',
 'Marrero',
 'West New York',
 'Glendora',
 'Peabody',
 'Gloucester',
 'Moore',
 'Waukesha',
 'Placentia',
 'Goshen',
 'Euless',
 'Petersburg',
 'San Pablo',
 'Plainfield',
 'Troy',
 'Poway',
 'Bonita Springs',
 'Urbana',
 'Niagara Falls',
 'Mason',
 'Bartlett',
 'Painesville',
 'Columbus',
 'Apple Valley',
 'Hoboken',
 'Paramount',
 'Levittown',
 'Spring',
 'Brookline',
 'Owings Mills',
 'North Miami',
 'Port Arthur',
 'West Sacramento',
 'Stratford',
 'Oregon City',
 'Anderson',
 'Milford',
 'Harrisburg',
 'Lancaster',
 'Oshkosh',
 'Zanesville',
 'Kingman',
 'Tigard',
 'Middletown',
 'Hollister',
 'Martinsburg',
 'Middletown',
 'Hutchinson',
 'Lenexa',
 'Redford',
 'East Hartford',
 'Homestead',
 'Chantilly',
 'Vicksburg',
 'South Hill',
 'Cathedral City',
 'Pine Bluff',
 'Irondequoit',
 'Garner',
 'Binghamton',
 "Coeur d'Alene",
 'Smyrna',
 'Salina',
 'North Fort Myers',
 'Parkersburg',
 'Pinellas Park',
 'Portage',
 'Mentor',
 'Kaneohe',
 'Clayton',
 'Downers Grove',
 'Sebring',
 'Highland',
 'Wake Forest',
 'Methuen',
 'West Orange',
 'Frankfort',
 'Danville',
 'Murray',
 'Lakewood',
 'Old Bridge Township',
 'Normal',
 'Lebanon',
 'Johns Creek',
 'Battle Creek',
 'Sheboygan',
 'East Brunswick',
 'Decatur',
 'Hammond',
 'Apex',
 'Buckeye',
 'Lakeville',
 'Richland',
 'Donna',
 'Saint Louis Park',
 'Wahiawa',
 'Roseville',
 'Galveston',
 'Menifee',
 'Cleveland Heights',
 'Castro Valley',
 'Aliso Viejo',
 'Olive Branch',
 'Perth Amboy',
 'Delaware',
 'Lincoln',
 'Tuckahoe',
 'Apache Junction',
 'Twin Falls',
 'Fort Washington',
 'New Albany',
 'Hempfield Township',
 'Mount Vernon',
 'Palm Desert',
 'Cuyahoga Falls',
 'Glenview',
 'Bedford',
 'Longwood',
 'Draper',
 'Wallingford',
 'Lawrence',
 'Howell',
 'Moline',
 'West Seneca',
 'Altoona',
 'Sammamish',
 'Spanaway',
 'Washington Township',
 'Doral',
 'Strongsville',
 'Hilo',
 'Grove City',
 'Pittsfield',
 'Crossville',
 'North Bethesda',
 'Longview',
 'Egg Harbor Township',
 'Bloomfield Hills',
 'Mandeville',
 'Elmhurst',
 'Diamond Bar',
 'Martinez',
 'Bloomfield',
 'Coral Gables',
 'Clarkston',
 'Greenwood',
 'Fairfield',
 'Asheboro',
 'Richmond',
 'Attleboro',
 'Pocatello',
 'Charlottesville',
 'Edmonds',
 'Desoto',
 'York',
 'Chesterfield',
 'Del Rio',
 'Campbell',
 'Roseburg',
 'Arlington',
 'Cedar Park',
 'Desert Hot Springs',
 'Rogers',
 'Enfield',
 'Burke',
 'Dekalb',
 'Henrietta',
 'Orangeburg',
 'Hobbs',
 'Concord',
 'Brunswick',
 'Chesterfield',
 'Catonsville',
 'Plymouth',
 'Penn Hills',
 'Bell Gardens',
 'Alpharetta',
 'Thibodaux',
 'Mount Juliet',
 'Taunton',
 'Charleston',
 'Everett',
 'Manchester',
 'Prattville',
 'Palm Springs',
 'Potomac',
 'Hudson',
 'Oakland Park',
 'Monrovia',
 'Dunwoody',
 'Joplin',
 'La Porte',
 'Clifton Park',
 'Freeport',
 'Claremore',
 'Lehi',
 'San Jacinto',
 'Westfield',
 'Woonsocket',
 'Cypress',
 'Lakeside',
 'Auburn',
 'Hoover',
 'Shakopee',
 'Haltom City',
 'Sherman',
 'Pine Hills',
 'Linden',
 'Collierville',
 'Hopkinsville',
 'Crestview',
 'Brea',
 'Milledgeville',
 'Cumberland',
 'Fair Oaks',
 'Wilkes-Barre',
 'Merritt Island',
 'Grapevine',
 'Norwich',
 'Kearny',
 'La Puente',
 'Aiea',
 'Gig Harbor',
 'Peachtree Corners',
 'Holyoke',
 'Eureka',
 'North Brunswick',
 'Elkton',
 'Blue Springs',
 'Fenton',
 'Buford',
 'Hoffman Estates',
 'Crystal Lake',
 'Salem',
 'State College',
 'Tonawanda',
 'Germantown',
 'New Berlin',
 'Lake Oswego',
 'Evans',
 'Grass Valley',
 'Menlo Park',
 'Levittown',
 'Cedar Hill',
 'Sarasota',
 'Merrillville',
 'Streamwood',
 'Port Huron Township',
 'Ankeny',
 'Franklin Township',
 'Fort Pierce',
 'Bountiful',
 'Wooster',
 'Georgetown',
 'Hillsborough',
 'Towson',
 'Cutler Bay',
 'Brighton',
 'Manassas',
 'Enterprise',
 'Nicholasville',
 'Manheim Township',
 'Palm Beach Gardens',
 'Owasso',
 'Winter Springs',
 'Thomasville',
 'Littleton',
 'Elizabeth City',
 'Winder',
 'Rock Island',
 'Lincoln Park',
 'Chester Township',
 'Moorhead',
 'Middle River',
 'Chesterfield',
 'Gonzales',
 'Los Lunas',
 'Carol Stream',
 'Euclid',
 'Brookhaven',
 'Kankakee',
 'Hallandale',
 'Bonney Lake',
 'Ramona',
 'Harvey',
 'Addison',
 'Marlborough',
 'Gallatin',
 'Moses Lake',
 'Montclair',
 'Wheeling',
 'Maplewood',
 'Alamogordo',
 ...]

In [17]:
meancrime
dfmeancrime = pd.DataFrame(data=meancrime, index=range(51), columns=["mean"])
dfmeancrime

         mean
0    433.0000
1    633.8500
2    437.7500
3    495.5750
4    446.8250
5    325.5625
6    281.1250
7    598.6750
8   1313.9875
9    572.0875
10   414.7500
11   261.8750
12   225.4750
13   451.7500
14   341.5250
15   276.0375
16   381.5125
17   246.7250
18   587.1000
19   123.2750
20   537.3375
21   433.6375
22   477.3500
23   245.0125
24   279.5375
25   473.6375
26   302.5875
27   281.1125
28   658.7625
29   184.9500
30   302.7625
31   612.7250
32   396.2750
33   383.9000
34   245.3375
35   317.1250
36   475.5500
37   254.8500
38   367.8250
39   246.1500
40   619.7125
41   279.4375
42   649.5250
43   448.9000
44   217.9625
45   130.6250
46   219.8375
47   311.1375
48   297.8375
49   272.4750
50   218.5500